version: '2'

services:
  nginxProjectXYZ:
    build:
      context: .
    image: ${DOCKER1_IP}:1337/devops/project-xyz:${IMAGE_TAG}
    # UCP access labels are case sensitive - match UCP GUI
    labels:
      - "com.docker.ucp.access.label=ProjectXYZ"
    ports:
      - "8080:80"