version: '2'

services:
  nginxProjectXYZ:
    # NOTE: replace hardcode IP for your machine
    image: 172.28.128.5:1337/devops/project-xyz:2.0.0
    # UCP access labels are case sensitive - match UCP GUI
    labels:
      - "com.docker.ucp.access.label=ProjectXYZ"
    ports:
      - "8080:80"